### ISSUE TITLE
bedgenerator vs bedtools

### ISSUE THREAD

**Issue by tseemann** [schultzm/p2xkit#1]
https://github.com/schultzm/p2xkit/blob/master/p2xkit/utils/bedgenerator_largecontigs.py#L11-L15

1. this will load the whole genome into RAM just to get the max contig size? (and the IDs)
maybe use `seqkit stats`?

2. if it is making chunks of a bigger genome, maybe `bedtools makewindows` ?
https://daler.github.io/pybedtools/autodocs/pybedtools.bedtool.BedTool.window_maker.html

**Comment by schultzm** [comment]
thanks.  I didn't end up using this.  great tip though.  `bedtools makewindows`!

**Comment by tseemann** [comment]
Your code still loads the whole human genome into RAM though?
just to get max_length ?
does pybedtools exist?
